### ISSUE TITLE
Don't allow withdrawal of locked tokens

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_tft_bridge#104]
Currently it's possible to withdraw locked tokens back to Stellar, this should not be possible.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The issue was fixed and i wasn't able to withdraw any of my locked tokens.

[TF DASHBOARD (14).webm](https://user-images.githubusercontent.com/101194226/206442239-96fe53d1-e084-4eb1-bb81-c1b1a735b7f0.webm)

> In the video above all the balance of the twin is locked but it didn't appear in the dashboard because of this https://github.com/threefoldtech/tfgrid_dashboard/issues/416
