### ISSUE TITLE
Bridge is refunding deposits from Stellar

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_tft_bridge#40]
I attempted depositing TFT from Stellar to both mainnet and testnet TF Chain, using a QR code generated in the portal. In both cases, the TFT was refunded to my Stellar wallet.

Also reported by a user via Crisp.

**Comment by DylanVerstraete** [comment]
Can we have the transaction hashes for transfers?

**Comment by DylanVerstraete** [comment]
I think I already see what the issue is, the user is trying to bridge only 1 TFT, while the fee for depositing to TFchain is 1 TFT. That is why the bridge is refunding this transaction, the user needs to send more than 1 TFT

**Comment by scottyeager** [comment]
Thanks Dylan. My tests were done with 1 TFT. I'm checking with the other user and will report back with their transactions details.

**Comment by scottyeager** [comment]
Crisp user was also sending 1 TFT transactions. I have advised to try a larger amount.
