### ISSUE TITLE
Create release for the TFChain Bridge

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/tfchain_tft_bridge#52]
is it live on mainnet? testnet?
if yes, what is the main release about? which number? is it v0.1.0? can you please make a github release? only found tags so far.
whats next... are we upgrading the bridge this sprint? if yes i need to make a v0.2.0 project, and we need to spec it.
if no upgrade needed than we just need to make the last release note.

**Comment by robvanmieghem** [comment]
A 1.0.0 release is indeed needed

**Comment by robvanmieghem** [comment]
@sasha-astiadi I updated the main readme so it states what this repo is about.I will create the 1.0.0 release.

**Comment by sasha-astiadi** [comment]
@robvanmieghem thank you. do we need a project v1.1.0 this sprint? or this bridge is stable enough for now

**Comment by robvanmieghem** [comment]
@sasha-astiadi There is no release planned for the current open issues.

**Comment by sasha-astiadi** [comment]
> @sasha-astiadi I updated the main readme so it states what this repo is about.I will create the 1.0.0 release.

yeah but its not enough. 1 line description is not enough.
which domain should user go to? mainnet? testnet? 
link to documentation if any

**Comment by DylanVerstraete** [comment]
https://github.com/threefoldtech/tfchain_tft_bridge/releases/tag/v1.0.3
