### ISSUE TITLE
Bridges on testnet and mainnet are refunding each other in a loop

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_tft_bridge#58]
I don't know how this happened but, seems like someone transfered 4 TFT from the bridge on Testnet to the bridge on Mainnet and now they are stuck in a refunding loop. 

testnet bridge account: https://stellar.expert/explorer/public/account/GA2CWNBUHX7NZ3B5GR4I23FMU7VY5RPA77IUJTIXTTTGKYSKDSV6LUA4

mainnet bridge account:
https://stellar.expert/explorer/public/account/GBNOTAYUMXVO5QDYWYO2SOCOYIJ3XFIP65GKOQN7H65ZZSO6BK4SLWSC

**Comment by DylanVerstraete** [comment]
Can be fixed if we add some sort of list of excluded addresses in the bridge startup configuration

**Comment by robvanmieghem** [comment]
did someone withdraw from a chain to the bridge adress of the other chain?

**Comment by robvanmieghem** [comment]
Instead of excluded addresses  I would simply not return deposits that have a `MEMO_RETURN ` in the transaction. This pin-pong can occur not only between tfchain-stellar bridge instances but also with one of these and the bsc bridge for instance.
