### ISSUE TITLE
The bridge UI is not used , but the code is still here

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/tfchain_tft_bridge#60]
as stated in https://github.com/threefoldtech/tfchain_tft_bridge/issues/56#issuecomment-1033707500 , the bridge UI is not used. It's confusing if dead and unmaintained code is still here.

**Comment by DylanVerstraete** [comment]
https://github.com/threefoldtech/tfchain_tft_bridge/commit/935957b9ad4c10d270ae33e78d5d019e5400b4e8
