### ISSUE TITLE
Didn't receive withdrawn TFTs to my TFConnect wallet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfchain_tft_bridge#87]
I was testing the Withdraw function from the Dashboard on testnet and after doing 2 transactions the first with `4 TFTs` and the second with `2 TFTs`, i didn't receive any of them and the TFTs were deducted from my account.

 and i checked my latest transactions from [Stellar](https://stellar.expert/explorer/public/account/GBXZBZUGGAQWUG44AHDBYQ5I6ZL35BKVXBI233FUJVIAQJUG6IM2OP4J) and i didn't see any signs of the 2 transactions i mentioned above.

and here is a gif of the second transaction showing that there were no errors from the dashboard.

![TF DASHBOARD (5)](https://user-images.githubusercontent.com/101194226/182026776-3d5abfcc-1856-4cd5-9f04-8341771d92ed.gif)

The 2 transactions were from `twin 451` on testnet to my TFConnect wallet `GBXZBZUGGAQWUG44AHDBYQ5I6ZL35BKVXBI233FUJVIAQJUG6IM2OP4J`

**Comment by DylanVerstraete** [comment]
The withdraw should have been processed. Can you please check?

**Comment by DylanVerstraete** [comment]
was because of https://github.com/threefoldtech/tfchain_tft_bridge/issues/85

**Comment by mohamedamer453** [comment]
Yep i checked my wallet now and it was successfully processed.

**Comment by mohamedamer453** [comment]
The same issue happened again on testnet on the same twin `451` and i was withdrawing to the same TFConnect wallet `GBXZBZUGGAQWUG44AHDBYQ5I6ZL35BKVXBI233FUJVIAQJUG6IM2OP4J`.

i tried to withdraw from the dashboard two times today and i didn't receive any of the tfts, the first transaction was done almost 4-5 hours ago and the amount withdrawn was `3TFT` and the second one was 30 mins ago and the amount was `2TFT`.

**Comment by DylanVerstraete** [comment]
Bridge on testnet was stuck due to horizon issues, withdraws are processed now. can you check please? :)

**Comment by DylanVerstraete** [comment]
We need some proper monitoring in place for these things...

**Comment by mohamedamer453** [comment]
Yep it's working now, TFTs successfully received and they appeared in my TFConnect wallet.

![image](https://user-images.githubusercontent.com/101194226/192151165-09be364f-023f-4e21-ab3f-fdbb43cdac53.png)
